- hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  tasks:

    - name: jboss-py
      pip:
        name: https://github.com/jairojunior/jboss-py/archive/master.zip

    - name: Configure datasource
      jboss_resource:
        name: "/subsystem=datasources/data-source=DemoDS"
        state: present
        attributes:
          driver-name: h2
          connection-url: "jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
          jndi-name: "java:jboss/datasources/DemoDS"
          user-name: sa
          password: sa
          min-pool-size: 20
          max-pool-size: 40
      register: result

    - debug:
        msg: "{{ result }}"

    - name: Undeploy hawt.io
      jboss_deployment:
        name: hawtio.war
        state: absent
      register: deploy

    - debug:
        msg: "{{  deploy }}"
